name: Main
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  ci:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        ruby: [jruby, 2.4, 2.5, 2.6, 2.7, 3.0, truffleruby-head]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Conditionally configure bundler via environment variables as advised
    #   * https://github.com/ruby/setup-ruby#bundle-config
    - name: Set bundler environment variables
      run: |
        echo "BUNDLE_WITHOUT=checks:docs" >> $GITHUB_ENV
      if: matrix.ruby != 3.0

    # Use 'bundler-cache: true' instead of actions/cache as advised:
    #   * https://github.com/actions/cache/blob/main/examples.md#ruby---bundler
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - run: bundle exec rspec

    - run: bundle exec rubocop
      if: matrix.ruby == 3.0

    - run: |
        bundle exec yard doctest
        bundle exec dokaz
      if: matrix.ruby == 3.0

    - name: Run benchmarks on Ruby 2.7 or 3.0
      run: |
        BUNDLE_GEMFILE=benchmarks/Gemfile bundle install --jobs 4 --retry 3
        BUNDLE_GEMFILE=benchmarks/Gemfile bundle exec ruby benchmarks/benchmarks.rb
      if: matrix.ruby == '2.7' || matrix.ruby == '3.0'
